# run `docker build -t librarian .` in the repository root prior to using this file
version: '3'
services:
  librarian:
    container_name: librarian
    image: librarian:latest
    command: >
      node index.js
    volumes:
      - <your-repository-location>:/usr/src/bot
      - <your-config-location>:/.store
    environment:
      - TZ=<your-timezone>
    restart: unless-stopped