# run `docker build -t librarian .` in the repository root prior to using this file
version: '3'
services:
  librarian:
    container_name: librarian
    image: librarian:latest
    command: >
      node index.js
    volumes:
      - ${REPOSITORY_LOCATION}:/usr/src/bot
      - ${CONFIG_LOCATION}:/.store
    environment:
      - TZ=${TIMEZONE}
    restart: unless-stopped